# Generated by Django 3.1.7 on 2021-09-28 18:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'Code Must be 4 characters')])),
                ('name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(3, 'Name min 3 and max 35 characters long')])),
                ('mobile', models.CharField(max_length=14)),
                ('date_of_birth', models.DateField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.dept')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.gender')),
            ],
        ),
    ]
